# Generated by Django 4.1.7 on 2023-03-25 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Geo', '0006_geo_masked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geo',
            name='masked',
        ),
    ]
